### ISSUE TITLE
Two’s Complement of 0 Produces Incorrect Result

### ISSUE THREAD

**Issue by andypleasants** [AnthonyH93/HexaCalc#6]
When on the binary calculator performing two’s complement on 0 produces an incorrect result of all 1s (-1).

Running the operation again produces 1.

**Comment by AnthonyH93** [comment]
Thank you for reporting this bug. I have confirmed the issue and will fix it for the upcoming update.

**Comment by AnthonyH93** [comment]
This issue has been fixed with the latest release (version 1.3.5) on the App Store (currently in review, but should be released within a day or two). Thanks again for reporting it!
