### ISSUE TITLE
Proposal to add history calculation view

### ISSUE THREAD

**Issue by FilippoZazzeroni** [AnthonyH93/HexaCalc#8]
Hi Anthony, 

I've added locally a view with the calculation history so far for the decimal view controller, if you give me access I can create a pull request. So far the view it's really simple, it's just to try to implement that feature.

**Comment by AnthonyH93** [comment]
Hello!

Thanks for reaching out, that's a great feature to add and something that would make the app better. I'd be interested in seeing the changes, if you create a fork of the repo and add your changes there then you should be able to open up a pull request.

**Comment by FilippoZazzeroni** [comment]
Hi @AnthonyH93 I created the pull request. You'll see that the implementation is very simple but it's just to check that the feature works
